//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Shop.Context
{
    using System;
    
    public partial class UserData
    {
        public int UserId { get; set; }
        public string Login { get; set; }
        public string RoleName { get; set; }
        public string EmployeeName { get; set; }
    }
}
